### DISCUSSION TITLE
Persistence / unauthenticated? What am I doing wrong

### DISCUSSION THREAD

**Discussion by jimapl** [quirrel-dev/quirrel#1118] [Q&A]
Hi all,

I've been running quirrel in my production app for a while now but I keep running into the same issue:
After a while, usually a week or so, quirrel.enqueue throws an unauthenticated error. 
Usually I have to rerun my curl cmd and run another production build afterwards. I'm pretty fed up with this routine as it basicly breaks my production app.

I am running redis & Quirrel with docker-compose
I'm somewhat new to working with docker so I hope anyone could help me out with my setup.

Here is my yaml file:

```yaml
version: "3.3"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - REDIS_PASSWORD=pass
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    networks:
      - redis-private
  quirrel:
    image: "ghcr.io/quirrel-dev/quirrel:sha-de34419"
    environment:
      - REDIS_URL=redis://:pass@redis:6379/0
      - QUIRREL_SERVER_URL=http://127.0.0.1:9181
      - NAME_OF_TOKEN=tokenName
      - PASSPHRASES=somepassprashes
    depends_on:
      - redis
    networks:
      - redis-private
      - quirrel-public
    ports:
      - "9181:9181"

networks:
  redis-private:
    external: false
  quirrel-public:
    external: true

volumes:
  redis_data:
    driver: local

#curlCmd=curl --user ignored:somepassprashes -X PUT http://localhost:9181/tokens/nameoftokenhere
````

How is this redis instance not persistent?

Hope someone can point my in the right direction.
& Thank you
