### DISCUSSION TITLE
Self-hosted Quirrel in Docker-Compose

### DISCUSSION THREAD

**Discussion by simonedelmann** [quirrel-dev/quirrel#853] [Q&A] [answered]
Hi there!
First of all: Great work, @Skn0tt ! Thanks for another very useful library.

I am trying to set up a self-hosted Quirrel instance with docker-compose. I try to archive that Quirrel and my Next-app are able to communicate via docker's internal networks. But when I try to enqueue some jobs, I get an `Unexpected Response` from Quirrel client and Quirrel server shows this in the log:

```
{"level":30,"time":1635502685735,"pid":1,"hostname":"ea492f4c6e2c","reqId":1,"req":{"method":"POST","url":"/queues/http%3A%2F%2FmyApp%3A3000%2Fapi%2Fqueue%2Fmail/batch","hostname":"quirrel:9181","remoteAddress":"172.18.0.5","remotePort":51190},"msg":"incoming request"}
{"level":30,"time":1635502685775,"pid":1,"hostname":"ea492f4c6e2c","reqId":1,"res":{"statusCode":404},"responseTime":38.611080000177026,"msg":"request completed"}
```

This is my docker-compose.yml: (the relevant parts only)

```
services:
  myApp:
    environment:
      QUIRREL_BASE_URL: http://myApp:3000
      QUIRREL_API_URL: http://quirrel:9181
      QUIRREL_TOKEN: ...
      QUIRREL_ENCRYPTION_SECRET: ...
    ports:
      - 3000:3000
  quirrel:
    image: ghcr.io/quirrel-dev/quirrel
```

It seems like my app is able to reach the Quirrel server, but the server seems not be able to call the queue api endpoint and refuses to enqueue the job. What am I missing here?

(I am aware that when deployed I could point QUIRREL_BASE_URL to the public domain. This is what I am currently doing, using quirrel.dev hosted version. But due to increasing API calls I want to move to self-hosted.)
