### DISCUSSION TITLE
How to acquire a token?

### DISCUSSION THREAD

**Discussion by deadcoder0904** [quirrel-dev/quirrel#856] [Q&A] [answered]
I am trying to self-host but facing some problems. I am currently trying to [acquire a token](https://docs.quirrel.dev/deploying#acquire-a-token), but I can't see where **QUIRREL_SERVER_URL** is set?

Is this the same as **QUIRREL_BASE_URL** or **QUIRREL_API_URL**? I'm confused.

Also, where should I set **PASSPHRASES**? Is it inside `.env` file where Quirrel picks it up or inside `docker-compose.yml` just under **REDIS_URL**?

```yml
version: '3.7'
services:
  quirrel:
    image: ghcr.io/quirrel-dev/quirrel:main
    environment:
      REDIS_URL: redis://redis
      PASSPHRASES: lalalalalalala
    ports:
      - '9181:9181'

  redis:
    image: redis
```

And when I do `curl` like:

```bash
$ curl --user ignored:{PASSPHRASE} -X PUT {QUIRREL_SERVER_URL}/tokens/{NAME_OF_TOKEN}
```

do I need to specify the fields inside `{}` or does it pick up from `.env`? I'm assuming **NAME_OF_TOKEN** can be anything set by me?

also, can i run complete quirrel setup using just docker locally or do i really need to deploy it on the server for it to work?
