### DISCUSSION TITLE
Unauthenticated regardless of token generation

### DISCUSSION THREAD

**Discussion by marek-hanzal** [quirrel-dev/quirrel#969] [Q&A]
Hello, I've managed to setup running Quirrel in Docker with all the env. variables, called token acquisition, but I'm getting unauthenticated on the quirrel side all the times.

Some hints, how to make this strange thing work? Only way I've currently found is to disable secrets at all.

Here is snapshot of my docker-compose:
![image](https://user-images.githubusercontent.com/13855126/157288326-5101bbf9-b039-4c10-864d-7526b5846ee9.png)

**Comment by Skn0tt** [comment]
One thing that stands out to me is that you're exposing Quirrel's `:9181` as `:49181`, while in the app you're using `:9181`. Could that be a problem? (maybe it's just a weird behaviour from Docker).

**Reply by Skn0tt** [reply]
Apart from that, it'd be great to have a text version of that `docker-compose.yml`. Would save me from typing this all out by hand ...

**Reply by marek-hanzal** [reply]
```yaml
version: '3'
services:
    app:
        image: marekhanzal/puff-smith:latest
        depends_on:
            - mariadb
        environment:
            DATABASE_URL: "postgresql://puff-smith:1234@postgres:5432/puff-smith?schema=public"
            QUIRREL_BASE_URL: 'http://app:3000'
            QUIRREL_API_URL: 'http://quirrel:9181'
            QUIRREL_TOKEN: '1800089494374-98ba-47ae-81bf-39b2d477abb0'
            QUIRREL_ENCRYPTION_SECRET: '06b3673c19b20f87d0d1232ee1cfd392'
            NEXTAUTH_URL: 'http://localhost:42000'
            NEXTAUTH_SECRET: '1234'
            NEXTAUTH_GITHUB_CLIENT_ID: '0a80a67836e180ee536e'
            NEXTAUTH_GITHUB_CLIENT_SECRET: 'dcfc933caa8676847cc9739a4ed0d6d1c43d21c5'
        networks:
            - db
            - quirrel
        ports:
            - "42000:3000"

    postgres:
        image: postgres:14.2
        ports:
            - "42532:5432"
        networks:
            - db
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
            POSTGRES_PASSWORD: 1234

    quirrel:
        image: ghcr.io/quirrel-dev/quirrel:main
        environment:
            DISABLE_TELEMETRY: 1
            REDIS_URL: 'redis://redis:6379'
            PASSPHRASES: '06b3673c19b20f87d0d1232ee1cfd392'
        ports:
            - "49181:9181"
        networks:
            - quirrel
            - redis

    redis:
        image: redis:6-alpine
        command: redis-server --appendonly yes
        networks:
            - redis

    adminer:
        image: adminer
        ports:
            - "42080:8080"
        networks:
            - db

networks:
    db:
    quirrel:
    redis:
```
